title: "Aaron Frey Personal Site"
sass:
  sass_dir: assets/css
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"