title: "Aaron Frey Personal Site"
sass:
  load_paths:
    - _sass
    - node_modules
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
include:
  - node_modules/